### ISSUE TITLE
[ci] drone.ioの導入

### ISSUE THREAD

**Issue by ujihisa** [ujihisa/sugot#4]
travisだと依存ライブラリのビルドで死ぬので自宅鯖でspigotのバイナリを一旦保存する方針にしようということで自宅鯖で動作するdrone.ioを早速試してみました。

kokoro/ubmono (ubuntu 14.04) に http://readme.drone.io/setup/install/ubuntu/ に準拠してインストールしました。nginxとポートフォワーディングで http://rukkit.com/drone/ でアクセスできます。

html帰ってきてるけど何もないように見える謎の状態なう。

**Comment by raa0121** [comment]
jsとcssだけ読み込まれてますね 謎い

**Comment by ujihisa** [comment]
I give up.
